// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testTypeScript.Models;

namespace testTypeScript.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testTypeScript.Models.Entities.M_CAR", b =>
                {
                    b.Property<int>("CAR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<string>("CATEGORY_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("DELETED")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("M_CAR_CATEGORYCAR_CATEGORY_ID")
                        .HasColumnType("int");

                    b.Property<string>("PLATE_NUMBER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRICE")
                        .HasColumnType("int");

                    b.Property<string>("UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VERSION")
                        .HasColumnType("int");

                    b.HasKey("CAR_ID");

                    b.HasIndex("M_CAR_CATEGORYCAR_CATEGORY_ID");

                    b.ToTable("M_CAR");
                });

            modelBuilder.Entity("testTypeScript.Models.Entities.M_CAR_CATEGORY", b =>
                {
                    b.Property<int>("CAR_CATEGORY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("DELETED")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("VERSION")
                        .HasColumnType("int");

                    b.HasKey("CAR_CATEGORY_ID");

                    b.ToTable("M_CAR_CATEGORY");
                });

            modelBuilder.Entity("testTypeScript.Models.Entities.M_SERVICE_ORDER", b =>
                {
                    b.Property<int>("ORDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ACTUAL_END_DTG")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ACTUAL_START_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("CAR_ID")
                        .HasColumnType("int");

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<string>("CUSTOMER_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DELETED")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ORDER_DURATION")
                        .HasColumnType("int");

                    b.Property<DateTime>("PLAN_END_DTG")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PLAN_START_DTG")
                        .HasColumnType("datetime2");

                    b.Property<string>("PLATE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRICE")
                        .HasColumnType("int");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<int>("TIME_CATEGORY")
                        .HasColumnType("int");

                    b.Property<string>("UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VERSION")
                        .HasColumnType("int");

                    b.HasKey("ORDER_ID");

                    b.ToTable("M_SERVICE_ORDER");
                });

            modelBuilder.Entity("testTypeScript.Models.Entities.M_STATUS", b =>
                {
                    b.Property<int>("STATUS_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("DELETED")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("VERSION")
                        .HasColumnType("int");

                    b.HasKey("STATUS_CODE");

                    b.ToTable("M_STATUS");
                });

            modelBuilder.Entity("testTypeScript.Models.Entities.M_TIME_CATEGORY", b =>
                {
                    b.Property<int>("TIME_CATEGORY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("DELETED")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED_DTG")
                        .HasColumnType("datetime2");

                    b.Property<int>("VERSION")
                        .HasColumnType("int");

                    b.HasKey("TIME_CATEGORY_ID");

                    b.ToTable("M_TIME_CATEGORY");
                });

            modelBuilder.Entity("testTypeScript.Models.Entities.M_CAR", b =>
                {
                    b.HasOne("testTypeScript.Models.Entities.M_CAR_CATEGORY", null)
                        .WithMany("M_CAR")
                        .HasForeignKey("M_CAR_CATEGORYCAR_CATEGORY_ID");
                });

            modelBuilder.Entity("testTypeScript.Models.Entities.M_CAR_CATEGORY", b =>
                {
                    b.Navigation("M_CAR");
                });
#pragma warning restore 612, 618
        }
    }
}
